'use strict';
const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const dist=path.join(root,'dist');
const {digitalCapabilities,infrastructureCapabilities,industries}=require('../src/content');
const T=require('../src/templates');
function rm(p){fs.rmSync(p,{recursive:true,force:true})}function copy(src,dst){fs.mkdirSync(dst,{recursive:true});for(const ent of fs.readdirSync(src,{withFileTypes:true})){const a=path.join(src,ent.name),b=path.join(dst,ent.name);ent.isDirectory()?copy(a,b):fs.copyFileSync(a,b)}}
function writeRoute(route,html){const dir=route==='/'?dist:path.join(dist,route.replace(/^\//,'').replace(/\/$/,''));fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html)}
rm(dist);copy(path.join(root,'public'),dist);
let home=fs.readFileSync(path.join(root,'src/homepage.html'),'utf8');
home=home.replaceAll('href="/contact/">Discuss a Project','href="/discuss-a-project/">Discuss a Project');
home=home.replaceAll('2367 Lavenham Road, Westgate, Harare, Zimbabwe','Harare, Zimbabwe');
home=home.replaceAll('2367 Lavenham Road<br />Westgate, Harare<br />Zimbabwe','Harare, Zimbabwe');
home=home.replaceAll('TECHGRITY SYSTEMS (PRIVATE) LIMITED','Techgrity Systems');
home=home.replaceAll('<strong>Head office</strong>','<strong>Location</strong>');
home=home.replaceAll('<h2>Head office</h2>','<h2>Location</h2>');
home=home.replace('href="/contact/#documents">Capability statements','href="/resources/">Capability statements');
home=home.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/,`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:'Techgrity Systems',url:'https://techgrity.co.zw/',logo:'https://techgrity.co.zw/assets/techgrity-primary-horizontal-approved.png',email:'business@techgrity.co.zw',address:{'@type':'PostalAddress',addressLocality:'Harare',addressCountry:'ZW'},description:'Techgrity Systems delivers digital systems, critical infrastructure and integrated technology solutions.'})}</script>`);
home=home.replace('<script src="/script.js" defer></script>','<script src="/site.js" defer></script>');
writeRoute('/',home);
const pages=[];
function add(route,html,indexable=true){writeRoute(route,html);pages.push({route,indexable})}
add('/capabilities/',T.capabilitiesOverview());
add('/capabilities/digital-systems/',T.capabilityLanding('digital'));
for(const item of digitalCapabilities)add(`/capabilities/digital-systems/${item.slug}/`,T.capabilityDetail(item,'digital'));
add('/capabilities/infrastructure/',T.capabilityLanding('infrastructure'));
for(const item of infrastructureCapabilities)add(`/capabilities/infrastructure/${item.slug}/`,T.capabilityDetail(item,'infrastructure'));
add('/capabilities/technology-supply/',T.technologySupply());
add('/industries/',T.industriesOverview());
for(const industry of industries)add(`/industries/${industry.slug}/`,T.industryDetail(industry));
add('/how-we-deliver/',T.howWeDeliver());
add('/company/',T.company());
add('/resources/',T.resources());
add('/contact/',T.contact());
add('/discuss-a-project/',T.discussProject());
add('/privacy/',T.legalPage('privacy'));
add('/terms/',T.legalPage('terms'));
add('/cookies/',T.legalPage('cookies'));
add('/404/',T.systemPage('404'),false);
add('/project-enquiry-received/',T.systemPage('project-enquiry-received'),false);
add('/document-request-received/',T.systemPage('document-request-received'),false);
add('/form-error/',T.systemPage('form-error'),false);
const publicRoutes=['/',...pages.filter(p=>p.indexable).map(p=>p.route)];
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${publicRoutes.map(r=>`  <url><loc>https://techgrity.co.zw${r}</loc></url>`).join('\n')}\n</urlset>\n`;
fs.writeFileSync(path.join(dist,'sitemap.xml'),sitemap);
fs.writeFileSync(path.join(dist,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://techgrity.co.zw/sitemap.xml\n');
fs.writeFileSync(path.join(dist,'route-manifest.json'),JSON.stringify({publicRoutes,systemRoutes:pages.filter(p=>!p.indexable).map(p=>p.route)},null,2));
console.log(`Built ${publicRoutes.length} public routes and ${pages.filter(p=>!p.indexable).length} system routes.`);
