'use strict';
process.env.FORM_DRY_RUN='1';
const assert=require('assert');const {validate}=require('../api/_forms');
const contact={name:'Test User',email:'test@example.com',category:'General business enquiry',message:'This is a valid synthetic enquiry for controlled testing.',privacyConsent:'on',startedAt:String(Date.now()-5000)};
assert.ok(validate('contact',contact).data);assert.ok(validate('contact',{...contact,email:'bad'}).error);assert.ok(validate('contact',{...contact,website:'bot'}).silent);
const project={projectName:'Test User',projectOrganisation:'Example Org',projectRole:'Engineer',projectEmail:'test@example.com',projectTelephone:'+263700000000',projectCountry:'Zimbabwe',projectCategory:'Networks & Fibre',projectIndustry:'Education & Research',projectLocation:'Harare',projectDescription:'A sufficiently detailed synthetic project description for validation testing.',expectedOutcomes:'Reliable service and documented acceptance.',currentEnvironment:'Existing network environment with controlled test data.',timescale:'Within 3–6 months',procurementStatus:'Early requirement definition',privacyConsent:'on',startedAt:String(Date.now()-5000)};
assert.ok(validate('project',project).data);assert.ok(validate('project',{...project,projectDescription:''}).error);
const documentRequest={requestName:'Test User',requestOrganisation:'Example Org',requestRole:'Procurement',requestEmail:'test@example.com',requestCountry:'Zimbabwe',document:'Corporate Capability Statement',reason:'Synthetic evaluation request for validation.',privacyConsent:'on',startedAt:String(Date.now()-5000)};
assert.ok(validate('document-request',documentRequest).data);assert.ok(validate('document-request',{...documentRequest,document:''}).error);
console.log('form validation tests passed');
