'use strict';

const { digitalCapabilities, infrastructureCapabilities, industries } = require('./content');

const SITE = 'https://techgrity.co.zw';
const EMAIL = 'business@techgrity.co.zw';
const PHONE_DISPLAY = '+263 78 330 4307';
const PHONE_HREF = '+263783304307';

const esc = (value='') => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list = (items, cls='check-list') => `<ul class="${cls}">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const cards = (items, {columns=3, links=false}={}) => `<div class="grid-${columns}">${items.map((x,i)=> links ? `<a class="card card-pad click-card" href="${x.href}"><span class="card-index">${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><span class="card-link">Explore ${esc(x.linkLabel || 'capability')} →</span></a>` : `<article class="card card-pad info-card"><span class="card-index">${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title || x)}</h3>${x.description?`<p>${esc(x.description)}</p>`:''}</article>`).join('')}</div>`;

function head({title,description,path,robots='index,follow',schema='WebPage'}){
  const canonical = `${SITE}${path}`;
  const jsonLd = {
    '@context':'https://schema.org','@type':schema,name:title,url:canonical,
    isPartOf:{'@type':'WebSite',name:'Techgrity Systems',url:SITE+'/'},
    publisher:{'@type':'Organization',name:'Techgrity Systems',url:SITE+'/',logo:{'@type':'ImageObject',url:SITE+'/assets/techgrity-primary-horizontal-approved.png'}}
  };
  return `<!doctype html><html lang="en" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${robots}"><meta name="theme-color" content="#031a3f"><link rel="canonical" href="${canonical}"><link rel="icon" href="/assets/favicon.png"><link rel="manifest" href="/site.webmanifest"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${SITE}/assets/techgrity-social-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/site.css"><script>document.documentElement.classList.remove('no-js');document.documentElement.classList.add('js');</script><script type="application/ld+json">${JSON.stringify(jsonLd)}</script></head>`;
}

function svg(type){
  const icons={mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',phone:'<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.78 19.78 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.78 19.78 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.69 2.8a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.28-1.28a2 2 0 0 1 2.11-.45c.9.33 1.84.56 2.8.69A2 2 0 0 1 22 16.92Z"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>'};
  return `<svg class="utility-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[type]}</svg>`;
}

function header(active=''){
  const digitalLinks=digitalCapabilities.map(x=>`<a href="/capabilities/digital-systems/${x.slug}/">${esc(x.navTitle||x.title)}</a>`).join('');
  const infraLinks=infrastructureCapabilities.map(x=>`<a href="/capabilities/infrastructure/${x.slug}/">${esc(x.title)}</a>`).join('');
  const industryLinks=industries.map(x=>`<a href="/industries/${x.slug}/">${esc(x.title)}</a>`).join('');
  const activeCls=(x)=>active===x?' class="active"':'';
  return `<a class="skip-link" href="#main">Skip to main content</a>
<div class="utility-bar"><div class="container utility-inner"><span>Intelligent systems. Trusted outcomes.</span><div class="utility-links"><a class="utility-item" href="mailto:${EMAIL}">${svg('mail')}<span>${EMAIL}</span></a><a class="utility-item" href="tel:${PHONE_HREF}">${svg('phone')}<span>${PHONE_DISPLAY}</span></a><span class="utility-item">${svg('pin')}<span>Harare, Zimbabwe</span></span></div></div></div>
<header class="site-header"><div class="container nav-wrap"><a class="brand" href="/" aria-label="Techgrity Systems home"><img src="/assets/techgrity-primary-horizontal-approved.png" width="1183" height="250" alt="Techgrity Systems"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav" aria-label="Open navigation menu"><span></span><span></span><span></span></button><nav class="primary-nav" id="primary-nav" aria-label="Primary navigation"><a${activeCls('home')} href="/">Home</a><div class="nav-dropdown"><button type="button" aria-expanded="false">Capabilities <i class="chevron"></i></button><div class="mega-menu"><div class="mega-column"><h3>Digital Systems &amp; AI</h3><a href="/capabilities/digital-systems/"><strong>Digital Systems overview</strong><small>Software, AI, automation, integration and data.</small></a>${digitalLinks}</div><div class="mega-column"><h3>Infrastructure &amp; Engineering</h3><a href="/capabilities/infrastructure/"><strong>Infrastructure overview</strong><small>Networks, data centres, telecoms, power and facilities.</small></a>${infraLinks}<a href="/capabilities/technology-supply/"><strong>Technology Supply &amp; Integration</strong></a></div></div></div><div class="nav-dropdown"><button type="button" aria-expanded="false">Industries <i class="chevron"></i></button><div class="mini-menu"><a href="/industries/"><strong>Industries overview</strong></a>${industryLinks}</div></div><a${activeCls('delivery')} href="/how-we-deliver/">How We Deliver</a><div class="nav-dropdown"><button type="button" aria-expanded="false">Company <i class="chevron"></i></button><div class="mini-menu"><a href="/company/">About Techgrity</a><a href="/company/#governance">Governance &amp; delivery</a></div></div><div class="nav-dropdown"><button type="button" aria-expanded="false">Resources <i class="chevron"></i></button><div class="mini-menu"><a href="/resources/">Capability statements</a><a href="/how-we-deliver/">Delivery methodology</a></div></div><a${activeCls('contact')} href="/contact/">Contact</a><a class="nav-cta" href="/discuss-a-project/">Discuss a Project →</a></nav></div></header>`;
}

function footer(){return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><img src="/assets/techgrity-primary-horizontal-approved.png" width="1183" height="250" alt="Techgrity Systems"><p>Digital systems and critical infrastructure for organisations that need reliable, accountable delivery.</p></div><div class="footer-column"><h3>Company</h3><a href="/company/">Company</a><a href="/how-we-deliver/">How We Deliver</a><a href="/contact/">Contact</a><a href="/discuss-a-project/">Discuss a Project</a></div><div class="footer-column"><h3>Capabilities</h3><a href="/capabilities/digital-systems/">Digital Systems &amp; AI</a><a href="/capabilities/infrastructure/">Infrastructure &amp; Engineering</a><a href="/capabilities/technology-supply/">Technology Supply &amp; Integration</a><a href="/industries/">Industries</a></div><div class="footer-column"><h3>Contact</h3><a href="mailto:${EMAIL}">${EMAIL}</a><a href="tel:${PHONE_HREF}">${PHONE_DISPLAY}</a><span>Harare, Zimbabwe</span><a href="/resources/">Capability statements</a></div></div><div class="footer-bottom"><span>© 2026 Techgrity Systems.</span><span><a href="/privacy/">Privacy</a> · <a href="/terms/">Terms</a> · <a href="/cookies/">Cookies</a></span></div></div></footer><button class="cookie-manage" type="button" data-cookie-manage>Cookie preferences</button><section class="cookie-panel" role="dialog" aria-modal="true" aria-labelledby="cookie-title" hidden data-cookie-panel><h2 id="cookie-title">Cookie preferences</h2><p>This website uses essential storage for security and preferences. Advertising and non-essential analytics are not currently used.</p><div class="cookie-actions"><button class="button button-primary" type="button" data-cookie-accept>Accept current settings</button><button class="button button-secondary" type="button" data-cookie-reject>Essential only</button></div></section><script src="/site.js" defer></script>`;}

function breadcrumb(items){return `<div class="breadcrumbs"><a href="/">Home</a>${items.map((x,i)=>`<span>›</span>${i===items.length-1?`<span>${esc(x.title)}</span>`:`<a href="${x.href}">${esc(x.title)}</a>`}`).join('')}</div>`;}

function heroBoard(title, rows, footerText='Integrated operational outcome'){
  return `<div class="hero-board" role="img" aria-label="${esc(title)}"><div class="board-kicker"><span class="status-dot"></span>Operational framework</div><strong class="board-title">${esc(title)}</strong><div class="board-stack">${rows.map((r,i)=>`<div class="board-row"><i>${String(i+1).padStart(2,'0')}</i><span><b>${esc(r.title||r)}</b>${r.detail?`<small>${esc(r.detail)}</small>`:''}</span>${r.tag?`<em>${esc(r.tag)}</em>`:''}</div>`).join('')}</div><div class="board-footer"><span>Requirement and context</span><span>→</span><strong>${esc(footerText)}</strong></div></div>`;
}

function heroText(item){
  const clean=String(item.hero||item.title).replace(/\.\s*$/,'');
  const accent=String(item.heroAccent||'').replace(/\.\s*$/,'');
  if(accent && clean.toLowerCase().endsWith(accent.toLowerCase())){
    return `${esc(clean.slice(0,clean.length-accent.length).trim())} <span>${esc(accent)}.</span>`;
  }
  return esc(clean)+'.';
}

function capabilitiesCollage(){return `<div class="hero-collage-card" role="img" aria-label="Digital systems, data-centre and network infrastructure working together"><div class="collage-image collage-people"></div><div class="collage-image collage-data"></div><div class="collage-image collage-network"></div><div class="collage-label"><span class="status-dot"></span><b>One integrated delivery model</b><small>Software · Infrastructure · Supply · Support</small></div></div>`;}

function digitalLandingVisual(){return `<div class="digital-hero-visual" role="img" aria-label="Professionals working with an operational digital system"><div class="digital-team-photo"></div><div class="digital-float digital-accountability"><span>Accountability</span><b>Roles · evidence · audit</b><i></i><i></i><i></i></div><div class="digital-float digital-workflow"><span>Operational workflow</span><b>7 stages connected</b><div></div></div><div class="digital-visual-label"><span class="status-dot"></span>Systems designed for real operations</div></div>`;}

function infrastructureLandingVisual(){return `<div class="infra-collage" role="img" aria-label="Connected data-centre, telecommunications and power infrastructure"><div class="infra-image infra-data"></div><div class="infra-image infra-telecom"></div><div class="infra-image infra-power"></div><div class="infra-collage-label"><span>Integrated engineering scope</span><b>Connectivity · Compute · Telecom · Power · Security</b></div></div>`;}

function digitalDetailVisual(item){return `<div class="workspace-visual" role="img" aria-label="${esc(item.title)} operational workspace"><div class="workspace-photo"></div><div class="workspace-panel"><div class="workspace-chrome"><i></i><i></i><i></i></div><p>${esc(item.title)}</p><strong>${esc(item.scope[0])}</strong><div class="workspace-rows">${item.scope.slice(0,4).map((x,i)=>`<div><i>${String(i+1).padStart(2,'0')}</i><span><b>${esc(x)}</b><small>${esc(item.deliverables[i]||'Controlled operational output')}</small></span><em>${['Complete','Active','Pending','Queued'][i]}</em></div>`).join('')}</div></div><div class="workspace-note"><span>Governed intelligence</span><b>Useful assistance. Defined responsibility.</b><small>Accountable people retain review and authority.</small></div></div>`;}

function infrastructureDetailVisual(item){
  const images={
    'networks-fibre':'cap-networks.jpg','data-centres-cloud':'cap-datacentre.jpg','telecom-radio':'cap-telecom.jpg','power-energy':'cap-power.jpg','security-smart-facilities':'cap-datacentre.jpg','civil-technical-works':'cap-technical.jpg'
  };
  return `<div class="infra-detail-visual" style="--infra-image:url('/assets/reference/${images[item.slug]||'cap-datacentre.jpg'}')" role="img" aria-label="${esc(item.title)} engineering environment"><div class="infra-detail-photo"></div><div class="infra-ops-panel"><div><span>Operational status</span><b>${esc(item.title)}</b><em><i></i> Controlled design</em></div><div class="infra-mini-map">${item.scope.slice(0,5).map((x,i)=>`<span style="--x:${18+i*16}%;--y:${i%2?64:34}%"><i></i><b>${String(i+1).padStart(2,'0')}</b></span>`).join('')}</div><div class="infra-metrics"><span><small>Scope</small><b>${item.scope.length} areas</b></span><span><small>Evidence</small><b>Defined</b></span></div></div></div>`;
}

function pageLayout({meta,active='',body,bodyClass=''}){return `${head(meta)}<body class="${bodyClass}">${header(active)}<main id="main">${body}</main>${footer()}</body></html>`;}

function standardHero({crumbs,title,lead,theme='light',heroClass='',board,primary='/discuss-a-project/',primaryLabel='Discuss a Project',secondary='/capabilities/',secondaryLabel='Explore Capabilities'}){
  return `<section class="page-hero ${theme} ${heroClass}"><div class="container page-hero-grid"><div>${breadcrumb(crumbs)}<p class="eyebrow">${esc(crumbs[crumbs.length-1].title)}</p><h1>${title}</h1><p class="hero-lead">${esc(lead)}</p><div class="hero-actions"><a class="button button-primary" href="${primary}">${esc(primaryLabel)} →</a>${secondary?`<a class="button ${theme==='dark'?'button-outline':'button-secondary'}" href="${secondary}">${esc(secondaryLabel)}</a>`:''}</div></div>${board}</div></section>`;}

function finalCta(title,copy='Share the requirement, operating environment and expected outcome.',label='Discuss a Project',href='/discuss-a-project/'){
  return `<section class="final-cta"><div class="container"><div class="cta-panel"><div><p class="eyebrow">Start with the requirement</p><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><a class="button button-primary" href="${href}">${esc(label)} →</a></div></div></section>`;
}

function capabilityDetail(item, division){
  const isDigital=division==='digital';
  const base=isDigital?'/capabilities/digital-systems/':'/capabilities/infrastructure/';
  const groupTitle=isDigital?'Digital Systems & AI':'Infrastructure & Engineering';
  const peers=isDigital?digitalCapabilities:infrastructureCapabilities;
  const title=`${item.title} | Techgrity Systems`;
  const heroRows=item.scope.slice(0,4).map((x,i)=>({title:x,detail:item.deliverables[i]||'',tag:i===0?'Scope':i===3?'Support':'Control'}));
  const body=standardHero({crumbs:[{title:'Capabilities',href:'/capabilities/'},{title:groupTitle,href:base},{title:item.title}],title:heroText(item),lead:item.description,theme:isDigital?'light':'dark',heroClass:isDigital?'digital-detail-hero':'infrastructure-detail-hero',board:isDigital?digitalDetailVisual(item):infrastructureDetailVisual(item),primaryLabel:`Discuss a ${isDigital?'Digital':'Technical'} Project`,secondary:base,secondaryLabel:`View ${groupTitle}`})+
  `<section class="section"><div class="container"><div class="section-head"><p class="eyebrow">What this capability covers</p><h2 class="section-title">A practical scope for the complete operating requirement.</h2><p class="section-lead">Each area below forms part of this capability and is delivered within the agreed project scope.</p></div>${cards(item.scope.map(x=>({title:x})),{columns:3})}</div></section>`+
  `<section class="section section-cool"><div class="container split"><div><p class="eyebrow">What we deliver</p><h2 class="section-title">Outputs structured for implementation, acceptance and support.</h2><p class="section-lead">The exact deliverables depend on project scope and are confirmed during discovery and design.</p></div>${list(item.deliverables)}</div></section>`+
  `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">Delivery approach</p><h2 class="section-title">From assessment to operational handover.</h2></div><ol class="lifecycle">${item.approach.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(x.split(' ').slice(0,2).join(' '))}</strong><small>${esc(x)}</small></li>`).join('')}</ol></div></section>`+
  `<section class="section section-dark"><div class="container matrix"><div><p class="eyebrow">Integration points</p><h2 class="section-title">This capability must work with the wider operating environment.</h2><p class="section-lead">Integration, security, monitoring and support boundaries are defined rather than assumed.</p>${list(item.integrations)}</div>${heroBoard('Connected operating layers',item.integrations.map((x,i)=>({title:x,detail:i===0?'Primary dependency':'Defined interface',tag:'Connected'})),'Controlled, supportable service')}</div></section>`+
  `<section class="section section-warm"><div class="container split"><div><p class="eyebrow">Relevant industries</p><h2 class="section-title">Applied according to sector responsibilities and constraints.</h2><p class="section-lead">The emphasis changes according to sector responsibilities, users, continuity needs and operating constraints.</p></div><div class="related-links">${item.industries.map(name=>{const ind=industries.find(x=>x.title===name);return `<a href="/industries/${ind?ind.slug:''}/"><span>${esc(name)}</span><b>→</b></a>`}).join('')}</div></div></section>`+
  `<section class="section"><div class="container"><div class="section-head"><p class="eyebrow">Related capabilities</p><h2 class="section-title">Capabilities commonly combined with this work.</h2></div>${cards(peers.filter(x=>x.slug!==item.slug).slice(0,3).map(x=>({title:x.title,description:x.description,href:`${base}${x.slug}/`})),{columns:3,links:true})}</div></section>`+
  finalCta(`Discuss a ${item.title.toLowerCase()} requirement.`,item.description,`Discuss a ${isDigital?'Digital':'Technical'} Project`);
  return pageLayout({meta:{title,description:item.description,path:`${base}${item.slug}/`,schema:'Service'},body,active:''});
}

function capabilityLanding(type){
  const digital=type==='digital';const items=digital?digitalCapabilities:infrastructureCapabilities;
  const group=digital?'Digital Systems & AI':'Infrastructure & Engineering';
  const path=digital?'/capabilities/digital-systems/':'/capabilities/infrastructure/';
  const description=digital?'Explore custom software, AI, automation, systems integration, data platforms and secure digital access for operational organisations.':'Explore enterprise networks, fibre, data centres, telecoms, power, security, smart facilities and technical infrastructure delivery.';
  const title=digital?'Operational systems built around people, data and accountable work.':'Critical infrastructure designed for reliable operation.';
  const boardRows=items.slice(0,4).map((x,i)=>({title:x.title,detail:x.description,tag:i===0?'Primary':'Connected'}));
  const matrixLayers=digital?[
    ['People & responsibilities','Operators','Managers','Customers','Partners'],['Applications & workflows','Services','Approvals','Field work','Reporting'],['Data & integration','APIs','Identity','Events','Analytics'],['Secure infrastructure','Cloud','Data centre','Networks','Backup']
  ]:[['Operations & service','People','Sites','Services','Controls'],['Applications & monitoring','Systems','Data','Identity','Visibility'],['Connectivity & compute','Networks','Data centre','Telecom','Cloud'],['Power & facilities','Energy','Access','Security','Environment']];
  const body=standardHero({crumbs:[{title:'Capabilities',href:'/capabilities/'},{title:group}],title:digital?'Operational systems built around <span>people, data and accountable work.</span>':'Critical infrastructure designed for <span>reliable operation.</span>',lead:description,theme:digital?'light':'dark',heroClass:digital?'digital-landing-hero':'infrastructure-landing-hero',board:digital?digitalLandingVisual():infrastructureLandingVisual(),primaryLabel:`Discuss a ${digital?'Digital':'Infrastructure'} Project`})+
  `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">${esc(group)} capabilities</p><h2 class="section-title">Specialist capability areas connected by one delivery discipline.</h2><p class="section-lead">Explore each area to understand its scope, delivery approach, integration points and support model.</p></div>${cards(items.map(x=>({title:x.title,description:x.description,href:`${path}${x.slug}/`})),{columns:3,links:true})}</div></section>`+
  `<section class="section section-cool"><div class="container matrix"><div><p class="eyebrow">Connected architecture</p><h2 class="section-title">Designed as layers, not isolated products.</h2><p class="section-lead">Responsibilities, systems, data, infrastructure, security and support are considered together.</p>${list(digital?['Human-centred workflows','Governed data and integration','Security and auditability','Operational support']:['Operating and site requirements','Connected infrastructure layers','Testing and commissioning','Supportable handover'])}</div><div class="matrix-board">${matrixLayers.map(row=>`<div class="matrix-layer"><span>${esc(row[0])}</span>${row.slice(1).map(x=>`<b>${esc(x)}</b>`).join('')}</div>`).join('')}<div class="matrix-base">Governance · evidence · testing · support</div></div></div></section>`+
  `<section class="section section-dark"><div class="container"><div class="section-head center"><p class="eyebrow">Delivery lifecycle</p><h2 class="section-title">Discover, design, build, integrate, commission and support.</h2></div><ol class="lifecycle">${['Discover','Design','Source','Build','Integrate','Commission','Support'].map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><strong>${x}</strong><small>${['Needs, environment and constraints','Architecture, controls and acceptance','Technology, licensing and partners','Implementation and configuration','Systems, data and operational alignment','Testing, evidence and handover','Monitoring, maintenance and improvement'][i]}</small></li>`).join('')}</ol></div></section>`+
  finalCta(`Plan a ${digital?'digital system':'critical infrastructure'} around the operation.`,description,`Discuss a ${digital?'Digital':'Infrastructure'} Project`);
  return pageLayout({meta:{title:`${group} | Techgrity Systems`,description,path,schema:'Service'},body});
}

function capabilitiesOverview(){
  const body=standardHero({crumbs:[{title:'Capabilities'}],title:'Digital systems and infrastructure <span>designed to work together.</span>',lead:'Techgrity combines software, engineering, technology supply and governed project delivery to help organisations move from requirement to operational outcome.',theme:'dark',heroClass:'capabilities-overview-hero',board:capabilitiesCollage(),primaryLabel:'Discuss a Project',secondary:'/how-we-deliver/',secondaryLabel:'How We Deliver'})+
  `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">One connected operating model</p><h2 class="section-title">Three capability areas. One accountable outcome.</h2></div>${cards([{title:'Digital Systems & AI',description:'Software, artificial intelligence, automation, data platforms and integrated operational systems.',href:'/capabilities/digital-systems/'},{title:'Technology Supply & Integration',description:'Requirements, sourcing, configuration, partner coordination, integration and handover.',href:'/capabilities/technology-supply/'},{title:'Infrastructure & Engineering',description:'Networks, fibre, data centres, telecommunications, power, security and technical infrastructure.',href:'/capabilities/infrastructure/'}],{columns:3,links:true})}</div></section>`+
  `<section class="section section-warm"><div class="container"><div class="section-head"><p class="eyebrow">Digital Systems &amp; AI</p><h2 class="section-title">Systems that make operations clearer, faster and more accountable.</h2></div>${cards(digitalCapabilities.map(x=>({title:x.title,description:x.description,href:`/capabilities/digital-systems/${x.slug}/`})),{columns:3,links:true})}</div></section>`+
  `<section class="section section-dark"><div class="container"><div class="section-head"><p class="eyebrow">Infrastructure &amp; Engineering</p><h2 class="section-title">Critical infrastructure designed for the operating environment.</h2></div>${cards(infrastructureCapabilities.map(x=>({title:x.title,description:x.description,href:`/capabilities/infrastructure/${x.slug}/`})),{columns:3,links:true})}</div></section>`+
  `<section class="section"><div class="container split"><div><p class="eyebrow">Technology Supply &amp; Integration</p><h2 class="section-title">One delivery capability across software and infrastructure.</h2><p class="section-lead">Requirements, specifications, sourcing, configuration, integration, commissioning and handover are connected in one governed process.</p><a class="card-link" href="/capabilities/technology-supply/">Explore Technology Supply &amp; Integration →</a></div>${heroBoard('Requirement-to-handover process',['Assess','Specify','Source','Configure','Integrate','Commission'],'Supportable operational handover')}</div></section>`+
  finalCta('Need several capabilities to work as one solution?');
  return pageLayout({meta:{title:'Technology Capabilities | Techgrity Systems',description:'Explore Techgrity capabilities across software, AI, automation, networks, fibre, data centres, telecoms, power and technical infrastructure.',path:'/capabilities/',schema:'CollectionPage'},body});
}

function technologySupply(){
  const stages=['Requirement definition','Technical specification','Sourcing and partner coordination','Delivery and staging','Configuration and integration','Testing and commissioning','Documentation and handover'];
  const body=standardHero({crumbs:[{title:'Capabilities',href:'/capabilities/'},{title:'Technology Supply & Integration'}],title:'Technology sourced, configured and commissioned <span>around the requirement.</span>',lead:'Techgrity moves from operating need and technical specification through sourcing, staging, configuration, integration, commissioning and support.',theme:'light',board:heroBoard('Specification-to-handover control',stages.slice(0,5).map((x,i)=>({title:x,detail:['Need, environment and constraints','Architecture, quantities and compatibility','Equipment, licensing and specialist coordination','Inspection, records and readiness','Configuration, interfaces and controls'][i],tag:i===0?'Input':i===4?'Integrate':'Gate'})),'Commissioned, documented solution'),primaryLabel:'Discuss a Supply Requirement'})+
  `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">What the capability covers</p><h2 class="section-title">Technology supply integrated with design, delivery and commissioning.</h2></div>${cards(['Requirements and specifications','Bills of materials and compatibility','Supplier and specialist coordination','Logistics, receiving and staging','Configuration and integration','Testing, commissioning and handover'].map(x=>({title:x})),{columns:3})}</div></section>`+
  `<section class="section section-cool"><div class="container"><div class="section-head"><p class="eyebrow">Requirement to handover</p><h2 class="section-title">A governed sequence with visible decisions and evidence.</h2></div><ol class="lifecycle">${stages.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(x.split(' ').slice(0,2).join(' '))}</strong><small>${esc(x)}</small></li>`).join('')}</ol></div></section>`+
  `<section class="section section-dark"><div class="container split"><div><p class="eyebrow">Integration and commissioning</p><h2 class="section-title">Equipment is accepted only when the connected solution works.</h2><p class="section-lead">Configuration, interfaces, power, networking, monitoring, testing and operating ownership remain part of the delivery scope.</p>${list(['Inspection and asset records','Configuration and compatibility checks','System and interface integration','Functional and resilience testing','Commissioning evidence and handover'])}</div>${heroBoard('Commissioning evidence',['Asset identity','Configuration record','Integration test','Acceptance result','Operating owner'],'Controlled operational handover')}</div></section>`+
  finalCta('Start with the operating requirement, not a predetermined product.');
  return pageLayout({meta:{title:'Technology Supply & Integration | Techgrity Systems',description:'Move from requirements and specifications to sourcing, installation, configuration, integration, commissioning and operational handover.',path:'/capabilities/technology-supply/',schema:'Service'},body});
}

function industriesOverview(){
  const body=standardHero({crumbs:[{title:'Industries'}],title:'Technology shaped around <span>real operating environments.</span>',lead:'Techgrity combines digital systems and physical infrastructure according to each sector’s responsibilities, constraints, risks and support needs.',theme:'light',board:heroBoard('Sector operating map',industries.slice(0,5).map((x,i)=>({title:x.title,detail:x.priorities[0],tag:i%2?'Infrastructure':'Digital + physical'})),'Sector-appropriate integrated solution'),primaryLabel:'Discuss Your Sector',secondary:'/capabilities/',secondaryLabel:'Explore Capabilities'})+
  `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">Six sector environments</p><h2 class="section-title">Distinct operating priorities—not duplicated marketing pages.</h2><p class="section-lead">Each sector page explains different users, responsibilities, technology layers and delivery controls.</p></div>${cards(industries.map(x=>({title:x.title,description:x.description,href:`/industries/${x.slug}/`,linkLabel:'sector'})),{columns:3,links:true})}</div></section>`+
  `<section class="section section-dark"><div class="container matrix"><div><p class="eyebrow">Integrated operating layers</p><h2 class="section-title">Digital systems depend on infrastructure, governance and support.</h2><p class="section-lead">Sector solutions are mapped across people, workflows, data, connectivity, compute, power, security and facilities.</p></div><div class="matrix-board"><div class="matrix-layer"><span>People &amp; responsibilities</span><b>Users</b><b>Operators</b><b>Managers</b><b>Partners</b></div><div class="matrix-layer"><span>Applications &amp; data</span><b>Services</b><b>Workflows</b><b>Integration</b><b>Analytics</b></div><div class="matrix-layer"><span>Connectivity &amp; compute</span><b>Networks</b><b>Data centre</b><b>Telecom</b><b>Cloud</b></div><div class="matrix-layer"><span>Resilience &amp; facilities</span><b>Power</b><b>Security</b><b>Monitoring</b><b>Support</b></div><div class="matrix-base">Governance · evidence · commissioning · support</div></div></div></section>`+
  finalCta('Discuss your sector, operating environment and delivery requirement.');
  return pageLayout({meta:{title:'Industries We Support | Techgrity Systems',description:'See how Techgrity combines digital systems and infrastructure for government, education, telecoms, energy, technology and commerce.',path:'/industries/',schema:'CollectionPage'},body,active:''});
}

function industryDetail(industry){
  const body=standardHero({crumbs:[{title:'Industries',href:'/industries/'},{title:industry.title}],title:`Technology for ${esc(industry.title)} <span>designed around the operation.</span>`,lead:industry.description,theme:'light',board:heroBoard(`${industry.title} operating model`,industry.priorities.slice(0,5).map((x,i)=>({title:x,detail:i%2?'Infrastructure and continuity':'Workflow, data and accountability',tag:i===0?'Priority':'Control'})),'Sector-appropriate operating outcome'),primaryLabel:'Discuss a Sector Requirement',secondary:'/industries/',secondaryLabel:'View All Industries'})+
  `<section class="section"><div class="container split"><div><p class="eyebrow">Operating priorities</p><h2 class="section-title">Technology must match responsibilities, risks and continuity needs.</h2><p class="section-lead">The priorities below shape discovery, design, acceptance and support.</p></div>${list(industry.priorities)}</div></section>`+
  `<section class="section section-cool"><div class="container"><div class="section-head center"><p class="eyebrow">Integrated requirements</p><h2 class="section-title">Digital and infrastructure layers planned together.</h2></div><div class="grid-2"><article class="card card-pad"><span class="card-index">Digital systems</span><h3>Applications, workflows, data and access</h3>${list(industry.digital)}</article><article class="card card-pad"><span class="card-index">Infrastructure &amp; engineering</span><h3>Connectivity, compute, communications and resilience</h3>${list(industry.infrastructure)}</article></div></div></section>`+
  `<section class="section"><div class="container"><div class="section-head"><p class="eyebrow">Representative project patterns</p><h2 class="section-title">Examples of how capabilities can be combined.</h2><p class="section-lead">These are prospective patterns, not claims of completed Techgrity projects.</p></div>${cards(industry.patterns.map(x=>({title:x,description:'A representative integrated requirement structured around sector responsibilities and operating constraints.'})),{columns:3})}</div></section>`+
  `<section class="section section-dark"><div class="container split"><div><p class="eyebrow">Delivery controls</p><h2 class="section-title">Sector relevance is carried into evidence and acceptance.</h2><p class="section-lead">Controls are adapted to project scale and risk without losing accountability.</p>${list(industry.controls)}</div>${heroBoard('Sector delivery controls',industry.controls.map((x,i)=>({title:x,detail:['Ownership and decision routes','Environment-specific design','Evidence against acceptance criteria','Supportable operational handover'][i],tag:'Required'})),'Accepted, supportable solution')}</div></section>`+
  `<section class="section section-warm"><div class="container"><div class="section-head"><p class="eyebrow">Relevant capabilities</p><h2 class="section-title">Continue into real capability pages.</h2></div>${cards([...digitalCapabilities.slice(0,2).map(x=>({title:x.title,description:x.description,href:`/capabilities/digital-systems/${x.slug}/`})),...infrastructureCapabilities.slice(0,2).map(x=>({title:x.title,description:x.description,href:`/capabilities/infrastructure/${x.slug}/`}))],{columns:4,links:true})}</div></section>`+
  finalCta(`Discuss a ${industry.title.toLowerCase()} technology requirement.`);
  return pageLayout({meta:{title:`Technology for ${industry.title} | Techgrity Systems`,description:industry.description,path:`/industries/${industry.slug}/`,schema:'Service'},body});
}

function howWeDeliver(){
  const stages=[['Discover','Stakeholders, current environment, constraints, risks and outcomes'],['Design','Architecture, specifications, integration, security and acceptance plan'],['Source','Bills of materials, licensing, compatibility and delivery scheduling'],['Build','Software development, implementation, configuration and quality evidence'],['Integrate','Interfaces, identity, data, networks and operating workflows'],['Commission','Testing, defect correction, documentation, training and handover'],['Support','Monitoring, maintenance, change handling and improvement']];
  const body=standardHero({crumbs:[{title:'How We Deliver'}],title:'From requirement to <span>operational handover.</span>',lead:'Techgrity structures delivery around defined responsibilities, technical evidence, controlled decisions and measurable operational outcomes.',theme:'dark',board:heroBoard('Project delivery control',stages.slice(0,5).map((x,i)=>({title:x[0],detail:x[1],tag:i===0?'Input':i===4?'Gate':'Stage'})),'Commissioned and supportable operation'),primaryLabel:'Discuss a Project',secondary:'/capabilities/',secondaryLabel:'Explore Capabilities'})+
  `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">Seven-stage lifecycle</p><h2 class="section-title">One lifecycle across digital, infrastructure and integrated projects.</h2></div><ol class="lifecycle">${stages.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><strong>${x[0]}</strong><small>${x[1]}</small></li>`).join('')}</ol></div></section>`+
  `<section class="section section-cool"><div class="container split"><div><p class="eyebrow">Responsibilities &amp; governance</p><h2 class="section-title">Clear responsibilities before work begins.</h2><p class="section-lead">Accountable ownership, decisions, risks, change and partner responsibilities are recorded rather than assumed.</p></div>${list(['Accountable owner and decision routes','Scope, dependencies and change control','Risk ownership and escalation','Partner and specialist responsibilities','Evidence, progress and acceptance reporting'])}</div></section>`+
  `<section class="section section-dark"><div class="container"><div class="section-head"><p class="eyebrow">Testing and acceptance</p><h2 class="section-title">Quality, security and risk are built into delivery.</h2></div>${cards(['Agreed acceptance criteria','Functional and technical testing','Integration and recovery testing','Defect classification and retesting','Commissioning and acceptance evidence','Documentation and training'].map(x=>({title:x})),{columns:3})}</div></section>`+
  `<section class="section"><div class="container split"><div><p class="eyebrow">Documentation &amp; handover</p><h2 class="section-title">Typical evidence depends on project scope.</h2><p class="section-lead">The exact handover pack is defined during design and may include the following.</p></div>${list(['Architecture and design documents','Configuration and asset records','Equipment schedules and as-built information','Test and commissioning results','Operating procedures and training records','Support and escalation information'])}</div></section>`+
  finalCta('Start with the requirement, not a predetermined product.');
  return pageLayout({meta:{title:'How We Deliver Technology Projects | Techgrity Systems',description:"Understand Techgrity's governed process from discovery and design through sourcing, integration, commissioning, handover and support.",path:'/how-we-deliver/'},body,active:'delivery'});
}

function company(){
  const body=standardHero({crumbs:[{title:'Company'}],title:'One company connecting digital systems and <span>critical infrastructure.</span>',lead:'Techgrity Systems brings together software, engineering, technology supply and accountable project delivery to support organisations in Zimbabwe and selected African markets.',theme:'light',board:heroBoard('Techgrity operating model',[{title:'Digital Systems & AI',detail:'Software, automation, data and integration',tag:'Division'},{title:'Infrastructure & Engineering',detail:'Networks, compute, telecoms, power and facilities',tag:'Division'},{title:'Technology Supply & Project Delivery',detail:'Specify, source, integrate and commission',tag:'Connect'}],'Integrated operational outcome'),primaryLabel:'Discuss a Project',secondary:'/capabilities/',secondaryLabel:'View Our Capabilities'})+
  `<section class="section"><div class="container split"><div><p class="eyebrow">Who we are</p><h2 class="section-title">Technology and engineering shaped around organisational outcomes.</h2></div><div><p class="section-lead">Techgrity Systems is a Zimbabwe-based technology and engineering company focused on the design, integration and support of digital systems and critical infrastructure.</p><p class="section-lead">We work from organisational requirements through implementation, commissioning and operational support.</p></div></div></section>`+
  `<section class="section section-cool"><div class="container"><div class="section-head center"><p class="eyebrow">Our structure</p><h2 class="section-title">Three connected areas with clear roles.</h2></div>${cards([{title:'Digital Systems & AI',description:'Software, automation, integration, data platforms and secure digital access.',href:'/capabilities/digital-systems/'},{title:'Infrastructure & Engineering',description:'Networks, data centres, telecoms, power, security and technical infrastructure.',href:'/capabilities/infrastructure/'},{title:'Technology Supply & Project Delivery',description:'Requirements, specifications, sourcing, integration, commissioning and handover.',href:'/capabilities/technology-supply/'}],{columns:3,links:true})}</div></section>`+
  `<section class="section"><div class="container"><div class="section-head"><p class="eyebrow">What guides our work</p><h2 class="section-title">Four operating principles.</h2></div>${cards(['Integrated thinking','Accountable delivery','Appropriate technology','Operational continuity'].map((x,i)=>({title:x,description:['Connect users, systems, infrastructure and responsibilities before defining the solution.','Make responsibilities, decisions, evidence and acceptance visible throughout delivery.','Select technology for the environment, outcome and long-term support capacity.','Include commissioning, documentation, knowledge transfer and support in delivery.'][i]})),{columns:4})}</div></section>`+
  `<section class="section section-dark"><div class="container split"><div><p class="eyebrow">Zimbabwe-based delivery</p><h2 class="section-title">Locally grounded. Regionally ambitious. Evidence conscious.</h2><p class="section-lead">Techgrity is building the capability and partnerships required to support organisations in Zimbabwe and selected African markets.</p></div>${list(['Local coordination and operating-context awareness','Qualified specialist and supplier coordination','Measured regional expansion aligned with delivery capacity','Clear boundaries for scope, partnerships and delivery responsibility'])}</div></section>`+
  `<section id="governance" class="section section-warm"><div class="container matrix"><div><p class="eyebrow">Governance &amp; delivery model</p><h2 class="section-title">Credibility comes from how work is controlled and handed over.</h2><p class="section-lead">Projects are structured around accountable ownership, controlled decisions, evidence, testing, commissioning and operational handover.</p><a class="card-link" href="/how-we-deliver/">Explore How We Deliver →</a></div>${heroBoard('Delivery governance',['Defined ownership','Scope and change control','Evidence and acceptance','Operational support'],'Supportable operational handover')}</div></section>`+
  `<section class="section"><div class="container split"><div><p class="eyebrow">Corporate information</p><h2 class="section-title">Public facts remain controlled and verifiable.</h2><p class="section-lead">Only confirmed public information appears. Legal registration details, exact address, leadership, partners and certifications remain omitted until formally approved.</p></div><div class="card card-pad"><div class="number-list"><div class="number-item"><i>01</i><span><b>Public brand</b><small>Techgrity Systems</small></span></div><div class="number-item"><i>02</i><span><b>Business email</b><small>${EMAIL}</small></span></div><div class="number-item"><i>03</i><span><b>Telephone</b><small>${PHONE_DISPLAY}</small></span></div><div class="number-item"><i>04</i><span><b>Location</b><small>Harare, Zimbabwe</small></span></div></div></div></div></section>`+
  finalCta("Talk to Techgrity about your organisation's next technology project.");
  return pageLayout({meta:{title:'Company | Techgrity Systems Zimbabwe',description:'Learn about Techgrity Systems, its Digital Systems and Infrastructure divisions, accountable delivery principles and Zimbabwe-based support.',path:'/company/',schema:'AboutPage'},body});
}

function resources(){
  const docs=['Corporate Capability Statement','Digital Systems Capability Statement','Infrastructure Capability Statement'];
  const body=standardHero({crumbs:[{title:'Resources'}],title:'Corporate documents for project and <span>procurement evaluation.</span>',lead:'Access approved Techgrity capability statements, delivery information and public company documents through a controlled resource centre.',theme:'light',board:heroBoard('Document access framework',[{title:'Approve',detail:'Content, scope and public-release decision',tag:'Gate'},{title:'Register',detail:'Version, date, owner and access model',tag:'Control'},{title:'Publish',detail:'Direct download or documented request',tag:'Access'},{title:'Maintain',detail:'Withdraw superseded files and preserve accuracy',tag:'Current'}],'Current, controlled document access'),primary:'/resources/#documents',primaryLabel:'View Available Documents',secondary:'/contact/',secondaryLabel:'Contact Business Development'})+
  `<section id="documents" class="section"><div class="container"><div class="section-head"><p class="eyebrow">Capability document families</p><h2 class="section-title">Capability statements prepared for structured evaluation.</h2><p class="section-lead">Each published document carries clear version, publication and access information.</p></div><div class="grid-3">${docs.map((x,i)=>`<article class="card document-card"><div class="document-cover ${i===1?'teal':''}"><span>${i===0?'Corporate':i===1?'Digital Systems':'Infrastructure'}</span><strong>${esc(x)}</strong></div><div class="document-body"><span class="document-state">Publication controlled</span><h3>${esc(x)}</h3><p>${esc(['Company positioning, integrated capability and delivery model.','Software, automation, integration, data and secure access.','Networks, data centres, telecoms, power and technical facilities.'][i])}</p><p class="form-note">Request the current approved version for business, procurement or project evaluation.</p></div></article>`).join('')}</div></div></section>`+
  `<section class="section section-cool"><div class="container split"><div><p class="eyebrow">Supporting company information</p><h2 class="section-title">Additional material follows the same publication discipline.</h2><p class="section-lead">Delivery summaries, approved company information and public policies may be added only when current and appropriate for release.</p></div>${list(['Delivery Methodology Summary','Approved company information','Privacy, terms and cookie policies','Procurement information approved for release'])}</div></section>`+
  `<section id="request" class="section section-warm"><div class="container split"><div><p class="eyebrow">Request a capability document</p><h2 class="section-title">Need information for a tender or evaluation?</h2><p class="section-lead">Use this route for legitimate business, procurement, partnership or project-evaluation needs.</p>${list(['Current approved version supplied','Request purpose and organisation recorded','Controlled business and procurement use','Appropriate delivery route confirmed'])}</div>${documentRequestForm()}</div></section>`+
  finalCta('Need project-specific information?', 'Contact business development or begin a structured project discussion.', 'Discuss a Project');
  return pageLayout({meta:{title:'Capability Statements & Resources | Techgrity Systems',description:'Access Techgrity capability statements, delivery information, approved company documents and document-request options.',path:'/resources/',schema:'CollectionPage'},body});
}

function formField({id,label,type='text',required=true,options=[],full=false,placeholder=''}){
  const control=type==='textarea'?`<textarea id="${id}" name="${id}" ${required?'required':''} placeholder="${esc(placeholder)}"></textarea>`:type==='select'?`<select id="${id}" name="${id}" ${required?'required':''}><option value="">Select an option</option>${options.map(x=>`<option>${esc(x)}</option>`).join('')}</select>`:`<input id="${id}" name="${id}" type="${type}" ${required?'required':''} placeholder="${esc(placeholder)}">`;
  return `<div class="field ${full?'full':''}"><label for="${id}">${esc(label)}${required?'':' <small>optional</small>'}</label>${control}<span class="field-error">Please review this field.</span></div>`;
}
function consent(){return `<div class="field full consent"><label><input type="checkbox" name="privacyConsent" required> I have read the <a href="/privacy/">Privacy Policy</a> and consent to the use of this information for handling this request.</label><span class="field-error">Consent is required.</span></div>`;}
function generalForm(){return `<form class="card form-shell" data-form="contact" action="/api/contact" method="post" novalidate><div class="form-grid">${formField({id:'name',label:'Name',placeholder:'Your full name'})}${formField({id:'organisation',label:'Organisation',required:false,placeholder:'Organisation name'})}${formField({id:'email',label:'Email',type:'email',placeholder:'name@organisation.co.zw'})}${formField({id:'telephone',label:'Telephone',required:false,placeholder:'+263 ...'})}${formField({id:'category',label:'Enquiry category',type:'select',full:true,options:['General business enquiry','Partnership or supplier enquiry','Media or institutional enquiry','Existing project or support enquiry','Other']})}${formField({id:'message',label:'Message',type:'textarea',full:true,placeholder:'Tell us what you need.'})}<input type="text" name="website" tabindex="-1" autocomplete="off" hidden>${consent()}<div class="field full"><button class="button button-primary" type="submit">Submit General Enquiry →</button><span class="form-note">Do not submit passwords, private keys or unnecessary sensitive information.</span></div></div><div class="form-status" role="status" aria-live="polite"></div></form>`;}
function documentRequestForm(){return `<form class="card form-shell" data-form="document-request" action="/api/document-request" method="post" novalidate><div class="form-grid">${formField({id:'requestName',label:'Name',placeholder:'Your full name'})}${formField({id:'requestOrganisation',label:'Organisation',placeholder:'Organisation name'})}${formField({id:'requestRole',label:'Job title',placeholder:'Your role'})}${formField({id:'requestEmail',label:'Work email',type:'email',placeholder:'name@organisation.co.zw'})}${formField({id:'requestCountry',label:'Country',placeholder:'Country'})}${formField({id:'document',label:'Document required',type:'select',options:['Corporate Capability Statement','Digital Systems Capability Statement','Infrastructure Capability Statement','All capability statements']})}${formField({id:'reason',label:'Reason for request',type:'textarea',full:true,placeholder:'Tell us what you are evaluating and what information you need.'})}<input type="text" name="website" tabindex="-1" autocomplete="off" hidden>${consent()}<div class="field full"><button class="button button-primary" type="submit">Submit Document Request →</button></div></div><div class="form-status" role="status" aria-live="polite"></div></form>`;}
function projectForm(){
 const categories=['Digital Systems & AI','Networks & Fibre','Data Centres & Cloud','Telecom & Radio','Power & Energy','Security & Smart Facilities','Civil & Technical Infrastructure','Technology Supply & Integration','Multiple or integrated capabilities','Not sure yet'];
 const industryNames=[...industries.map(x=>x.title),'Other'];
 return `<form class="card form-shell" data-form="project" action="/api/project" method="post" novalidate><div class="form-grid">${formField({id:'projectName',label:'Name',placeholder:'Your full name'})}${formField({id:'projectOrganisation',label:'Organisation',placeholder:'Organisation name'})}${formField({id:'projectRole',label:'Role or job title',placeholder:'Your role'})}${formField({id:'projectEmail',label:'Work email',type:'email',placeholder:'name@organisation.co.zw'})}${formField({id:'projectTelephone',label:'Telephone',placeholder:'+263 ...'})}${formField({id:'projectCountry',label:'Country',placeholder:'Country'})}${formField({id:'projectCategory',label:'Project category',type:'select',options:categories})}${formField({id:'projectIndustry',label:'Industry',type:'select',options:industryNames})}${formField({id:'projectLocation',label:'Project location',full:true,placeholder:'City, province or country'})}${formField({id:'projectDescription',label:'Project description',type:'textarea',full:true,placeholder:'Describe the requirement and current situation.'})}${formField({id:'expectedOutcomes',label:'Expected outcomes',type:'textarea',full:true,placeholder:'What should become possible or improve?'})}${formField({id:'currentEnvironment',label:'Current environment',type:'textarea',full:true,placeholder:'Describe existing systems, sites, constraints and dependencies.'})}${formField({id:'timescale',label:'Required timescale',type:'select',options:['Immediate or urgent requirement','Within 1–3 months','Within 3–6 months','Within 6–12 months','More than 12 months','Early planning or feasibility stage']})}${formField({id:'procurementStatus',label:'Procurement or tender status',type:'select',options:['Early requirement definition','Budgeting or feasibility','Preparing specifications or tender documents','Active request for quotation','Active tender or procurement process','Approved project awaiting delivery partner','Existing environment requiring support or improvement','Other']})}<input type="text" name="website" tabindex="-1" autocomplete="off" hidden>${consent()}<div class="field full"><button class="button button-primary" type="submit">Submit Project Enquiry →</button><span class="form-note">For security, attachments are not accepted through this form. An appropriate document-sharing route can be provided where required.</span></div></div><div class="form-status" role="status" aria-live="polite"></div></form>`;
}

function contact(){
 const body=standardHero({crumbs:[{title:'Contact'}],title:'Tell us what you need. <span>We will route it correctly.</span>',lead:'Use the general enquiry route, begin a structured project discussion or request an approved capability document.',theme:'light',board:heroBoard('Enquiry routing',[{title:'General enquiry',detail:'Company, partnership, supplier or existing-project question',tag:'General form'},{title:'Project requirement',detail:'Digital, infrastructure or integrated delivery need',tag:'Project form'},{title:'Capability document',detail:'Procurement, tender or evaluation material',tag:'Resources'}],'Appropriate business action'),primary:'/contact/#general',primaryLabel:'Send an Enquiry',secondary:'/discuss-a-project/',secondaryLabel:'Discuss a Project'})+
 `<section class="section"><div class="container"><div class="section-head center"><p class="eyebrow">Choose the right route</p><h2 class="section-title">Three clear contact actions.</h2></div>${cards([{title:'General Enquiry',description:'Company information, partnerships, suppliers, media or existing-project questions.',href:'/contact/#general'},{title:'Discuss a Project',description:'Describe an operating outcome, requirement, environment, constraints and timescale.',href:'/discuss-a-project/'},{title:'Request a Capability Statement',description:'Request approved corporate, Digital Systems or Infrastructure documents.',href:'/resources/#request'}],{columns:3,links:true})}</div></section>`+
 `<section id="general" class="section section-cool"><div class="container split"><div><p class="eyebrow">General enquiry</p><h2 class="section-title">A concise route for business questions.</h2><p class="section-lead">Project requirements and document requests use their dedicated routes so this form remains clear.</p>${list(['General business enquiry','Partnership or supplier enquiry','Media or institutional enquiry','Existing project or support enquiry','Other'])}</div>${generalForm()}</div></section>`+
 `<section class="section section-dark"><div class="container split"><div><p class="eyebrow">Direct contact</p><h2 class="section-title">Unable to use a form?</h2><p class="section-lead">Use the confirmed contact information below. No unverified response time, office address or business-hours promise is displayed.</p></div><div class="card card-pad"><div class="number-list"><div class="number-item"><i>01</i><span><b>Business email</b><small>${EMAIL}</small></span></div><div class="number-item"><i>02</i><span><b>Telephone</b><small>${PHONE_DISPLAY}</small></span></div><div class="number-item"><i>03</i><span><b>Location</b><small>Harare, Zimbabwe</small></span></div></div></div></div></section>`+
 finalCta('Choose the route that matches your requirement.','General enquiry, structured project discussion or capability-document request.','Discuss a Project');
 return pageLayout({meta:{title:'Contact Techgrity Systems',description:'Contact Techgrity Systems in Harare for digital systems, infrastructure, technology supply and general business enquiries.',path:'/contact/',schema:'ContactPage'},body,active:'contact'});
}

function discussProject(){
 const body=standardHero({crumbs:[{title:'Discuss a Project'}],title:'Tell us about the outcome <span>your organisation needs.</span>',lead:'Share the requirement, operating environment, constraints and expected timescale. Techgrity will use the information to identify the appropriate capability and next step.',theme:'light',board:heroBoard('Project enquiry structure',[{title:'Contact',detail:'Responsible person and organisation',tag:'Step 1'},{title:'Requirement',detail:'Outcome, category, industry and environment',tag:'Step 2'},{title:'Delivery context',detail:'Timescale, procurement status and constraints',tag:'Step 3'},{title:'Consent and submit',detail:'Review and secure server-side routing',tag:'Step 4'}],'Reviewed and routed enquiry'),primary:'/discuss-a-project/#project-form',primaryLabel:'Start Project Enquiry',secondary:'/contact/',secondaryLabel:'General Contact'})+
 `<section class="section section-warm"><div class="container split"><div><p class="eyebrow">Before you begin</p><h2 class="section-title">Early-stage requirements are acceptable.</h2><p class="section-lead">The form is designed to qualify and route the opportunity without forcing you to write a tender document.</p>${list(['Do not submit passwords, private keys or unnecessary personal data','Attachments remain disabled until secure handling is commissioned','Submission does not constitute a contract or guaranteed acceptance','Any proposal or commercial commitment is handled separately'])}</div>${heroBoard('What happens next',['Enquiry received and validated','Reviewed and routed','Clarification requested where needed','Discovery or capability discussion arranged'],'Separate scope or commercial process')}</div></section>`+
 `<section id="project-form" class="section"><div class="container"><div class="section-head"><p class="eyebrow">Project enquiry form</p><h2 class="section-title">Describe the requirement, context and expected outcome.</h2></div>${projectForm()}</div></section>`+
 `<section class="section section-dark"><div class="container"><div class="section-head center"><p class="eyebrow">What happens next</p><h2 class="section-title">Review, clarify and agree the appropriate next action.</h2></div>${cards(['Enquiry is reviewed and routed','Techgrity may request clarification','An appropriate discovery discussion may be arranged','Scope, proposal and commercial commitment are handled separately'].map(x=>({title:x})),{columns:4})}</div></section>`;
 return pageLayout({meta:{title:'Discuss a Technology Project | Techgrity Systems',description:'Share your software, network, data-centre, telecom, power or integrated infrastructure requirement with Techgrity Systems.',path:'/discuss-a-project/'},body});
}

function legalPage(type){
 const content={
  privacy:{
   title:'Privacy Policy',
   description:'Read how Techgrity Systems collects, uses, protects and retains personal information through its website and enquiry processes.',
   intro:'This policy explains how Techgrity Systems handles personal information provided through this website. It should be read together with any additional notice shown when a specific service or secure document-sharing process is used.',
   sections:[
    ['Who is responsible','Techgrity Systems is responsible for the personal information collected through this website. The public contact point for privacy questions and requests is business@techgrity.co.zw. Techgrity is based in Harare, Zimbabwe.'],
    ['Information we collect','We collect information that you choose to provide through general enquiries, project enquiries and capability-document requests. This may include your name, organisation, role, email address, telephone number, country, project location, enquiry content, procurement context and the documents you request. The website may also create limited technical records needed for security, abuse prevention, troubleshooting and reliable delivery.'],
    ['Why we use information','We use personal information to validate, receive, route and respond to legitimate business enquiries; evaluate project and document requests; arrange appropriate follow-up; protect the website and its users; maintain necessary business and security records; and comply with applicable legal obligations. We do not use website enquiries for unrelated direct marketing without an appropriate basis or separate permission.'],
    ['Consent and necessary processing','When you submit a form, you ask Techgrity to use the supplied information for the stated enquiry or request. Some processing may also be necessary to protect the website, maintain records, pursue legitimate business interests or comply with legal obligations. You may withdraw consent where processing depends on consent, although this does not affect processing already completed or information that must be retained for another lawful reason.'],
    ['Data minimisation and sensitive information','Please provide only information needed for the enquiry. Do not submit passwords, private keys, payment-card details, health information or other unnecessary sensitive personal information through the public forms. Project attachments are not accepted through the public project form; an appropriate controlled sharing route may be arranged when required.'],
    ['Who may receive information','Access is limited to authorised Techgrity personnel and service providers needed to host, secure and operate the website or deliver enquiry notifications. Providers act only for the relevant service purpose and are expected to apply appropriate confidentiality and security controls. We do not sell personal information.'],
    ['International service providers','Some hosting, security or communications providers may process information outside Zimbabwe. Where this occurs, Techgrity will assess the service and manage the transfer in accordance with applicable requirements and the sensitivity of the information involved.'],
    ['How long we keep information','Information is kept only for as long as reasonably necessary to handle the enquiry, maintain appropriate business and security records, resolve disputes and meet legal obligations. Retention may differ according to the type of enquiry, whether a business relationship follows and any applicable procurement or legal requirement. Information that is no longer required is deleted, anonymised or securely archived according to the relevant control.'],
    ['Security','Techgrity applies reasonable technical and organisational measures intended to protect personal information against unauthorised access, alteration, loss, disclosure or destruction. No internet transmission or storage system can be guaranteed to be completely secure, so confidential credentials or unnecessary sensitive material should not be submitted through public forms.'],
    ['Your rights','Subject to applicable law and reasonable identity verification, you may ask to be informed about the use of your personal information, request access, object to certain processing, or request correction or deletion of false or misleading information. Send requests to business@techgrity.co.zw and describe the information or enquiry concerned.'],
    ['Children','This corporate website and its enquiry forms are not intended for children. A person under eighteen should not submit personal information without the involvement of a parent, guardian or other authorised adult.'],
    ['Changes to this policy','We may update this policy when website functions, service providers or legal requirements change. The current version will be published on this page with its effective date.']
   ]
  },
  terms:{
   title:'Website Terms of Use',
   description:'Read the terms governing use of the Techgrity Systems website, its content, documents, enquiries and external links.',
   intro:'These terms govern access to and use of the Techgrity Systems website. By using the website, you agree to use it lawfully and in accordance with these terms.',
   sections:[
    ['Website purpose','This website provides corporate, capability, industry, delivery and contact information about Techgrity Systems. The content is general information and does not by itself create a contract, proposal, quotation, warranty, partnership, appointment or professional commitment.'],
    ['Accuracy and availability','Techgrity aims to keep public information accurate and useful but may correct, update, replace, suspend or withdraw website content without notice. Availability may be interrupted for maintenance, security, service-provider failure or circumstances outside Techgrity’s control.'],
    ['Capability and industry information','Capability descriptions and representative solution patterns explain the kinds of work Techgrity may undertake. They are not claims that a particular client project has been completed, that a specific result is guaranteed or that every service is immediately available in every location.'],
    ['Documents and downloads','A capability statement or other document is current only when it is displayed as an approved version with its publication information. Documents may be updated, replaced or withdrawn. They are provided for legitimate business, procurement, partnership or project-evaluation use and do not create a commercial commitment.'],
    ['Enquiries and submissions','Submitting a form does not guarantee acceptance of a requirement, a response within a particular period or a commercial relationship. You must provide information you are authorised to share and must not submit passwords, private keys, unlawful material, malicious code or unnecessary sensitive personal information. Any scope, proposal, price, timeline or contract is handled separately.'],
    ['Acceptable use','You must not use the website to interfere with its operation, attempt unauthorised access, probe security controls without permission, impersonate another person, infringe rights, distribute harmful material or send abusive or automated submissions. Techgrity may restrict access or reject submissions where necessary to protect the website and its users.'],
    ['Intellectual property','Unless otherwise stated, the Techgrity name, logo, website design, text, diagrams and published documents are owned by or licensed to Techgrity. You may view and use public material for legitimate evaluation. Reproduction, alteration, redistribution or commercial use beyond that purpose requires permission or another lawful basis.'],
    ['External links','External links may be provided for convenience or reference. Techgrity does not control third-party websites and is not responsible for their content, availability, security or privacy practices.'],
    ['Responsibility for decisions','You remain responsible for technical, procurement, financial and operational decisions made using general website information. Obtain an agreed scope and appropriate professional advice before relying on information for a specific implementation.'],
    ['Governing law','These terms are governed by the laws of Zimbabwe. Any dispute relating to the website is subject to the applicable processes and jurisdiction in Zimbabwe, unless a separate written agreement provides otherwise.'],
    ['Contact','Questions about these terms may be sent to business@techgrity.co.zw.']
   ]
  },
  cookies:{
   title:'Cookie Policy',
   description:'Understand the cookies and similar storage used by the Techgrity Systems website and how preferences can be managed.',
   intro:'This policy describes the cookies and browser storage used by the Techgrity Systems website. The current website does not use advertising or behavioural-marketing cookies.',
   sections:[
    ['Current use of browser storage','The website stores a small preference value in your browser under the name “techgrity-cookie-preference”. It records whether you selected “Essential only” or accepted the current settings so that the preference panel does not need to reopen on every page. The current settings contain no analytics or advertising category.'],
    ['Essential website functions','The site and its hosting environment may use technical mechanisms necessary to provide pages securely, prevent abuse, route forms and maintain service reliability. These mechanisms are not used to build advertising profiles.'],
    ['Analytics and marketing','Techgrity does not currently load non-essential analytics, advertising or cross-site tracking technologies through this website. If that changes, the new technology will not be treated as part of the current essential-only setting: this policy and the preference controls will be updated before it is enabled where consent is required.'],
    ['Managing preferences','Use the “Cookie preferences” control in the footer to reopen the preference panel. Selecting “Essential only” keeps non-essential technologies disabled. You can also clear website storage through your browser settings, which will cause the panel to appear again.'],
    ['Browser controls','Most browsers allow you to inspect, delete or block cookies and local storage. Blocking all storage may cause the preference panel to reappear, but it should not prevent access to the website’s core public content.'],
    ['Changes to this policy','The current storage inventory is based on the deployed website functions. We may update this policy when those functions or service providers change.']
   ]
  }
 }[type];
 const body=`<section class="page-hero light legal-hero"><div class="container page-hero-grid"><div>${breadcrumb([{title:content.title}])}<p class="eyebrow">Legal</p><h1>${esc(content.title)}</h1><p class="hero-lead">${esc(content.description)}</p><p class="policy-date">Effective 29 July 2026</p></div>${heroBoard(content.title,[{title:'Plain-language scope',detail:'What the policy covers',tag:'Clear'},{title:'Operationally accurate',detail:'Matches current website behaviour',tag:'Current'},{title:'Contact route',detail:'Questions and requests can be raised',tag:'Available'}],'Transparent website terms')}</div></section><section class="section"><div class="container legal"><p class="legal-intro">${esc(content.intro)}</p>${content.sections.map(([h,p])=>`<h2>${esc(h)}</h2><p>${esc(p)}</p>`).join('')}</div></section>`;
 return pageLayout({meta:{title:`${content.title} | Techgrity Systems`,description:content.description,path:`/${type}/`,schema:'WebPage'},body,active:''});
}

function systemPage(kind){
 const data={
  '404':{code:'404',title:'Page not found',copy:'The requested page could not be found. Use the routes below to continue.',actions:[['Home','/'],['Capabilities','/capabilities/'],['Contact','/contact/']]},
  'project-enquiry-received':{code:'Enquiry received',title:'Your project enquiry has been received',copy:'The submitted information has entered the controlled review route. Any scope, proposal or commercial commitment is handled separately.',actions:[['Home','/'],['How We Deliver','/how-we-deliver/']]},
  'document-request-received':{code:'Request received',title:'Your document request has been received',copy:'The request will be handled according to the document access model. No unavailable file is promised by this confirmation.',actions:[['Resources','/resources/'],['Contact','/contact/']]},
  'form-error':{code:'Submission problem',title:'We could not submit your request',copy:'Your entered information should remain available in the form. Retry or use the confirmed direct contact routes.',actions:[['Contact','/contact/'],['Discuss a Project','/discuss-a-project/']]}
 }[kind];
 const body=`<section class="system-state"><div class="system-state-inner"><p class="system-code">${esc(data.code)}</p><h1>${esc(data.title)}</h1><p class="hero-lead">${esc(data.copy)}</p><div class="hero-actions">${data.actions.map(([l,h],i)=>`<a class="button ${i?'button-secondary':'button-primary'}" href="${h}">${esc(l)}</a>`).join('')}</div></div></section>`;
 return pageLayout({meta:{title:`${data.title} | Techgrity Systems`,description:data.copy,path:kind==='404'?'/404/':`/${kind}/`,robots:'noindex,follow'},body});
}

module.exports={capabilitiesOverview,capabilityLanding,capabilityDetail,technologySupply,industriesOverview,industryDetail,howWeDeliver,company,resources,contact,discussProject,legalPage,systemPage};
